name: Deploying docker containers of django and postgres

on:
    workflow_call:
    workflow_dispatch:
    push:
       branches: [main]
    pull_request:
        branches: [main]
jobs:
  simple_build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create docker network
        run: |
          docker network create -d bridge our-library-net
      - name: Build django image
        run: |
          docker build -t my-django-image02:2.0.0 .
      - name: Run docker postgres container
        run: |
          docker-compose --env-file .env.stg up -d postgres_db04
      - name: Verifying net
        run: |
          docker inspect -f "{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}" postgres02
      - name: Run docker django container
        run: |
          docker-compose --env-file .env.stg up -d web04